
// Auto-generated by prebuild.ts — DO NOT EDIT
import '../.metadata/metadata.index';

import { Metadata } from 'golem-ts-sdk';
import { metadataCollection } from '../.metadata/metadata.index';

metadataCollection.forEach(mod => mod.add(Metadata, false));

let userModulePromise = import("../src/index.ts");

export default (async () => {
  const mod = await userModulePromise;
  return mod;
})();
