
// Auto-generated by prebuild.ts — DO NOT EDIT
import '../.metadata/metadata.index';
import { BaseMetadataLibrary, GlobalMetadata } from "rttist";

import { Metadata } from '@afsalthaj/golem-ts-sdk';
import { metadataCollection } from '../.metadata/metadata.index';

Metadata.clearMetadata("@afsalthaj/golem-ts-sdk");
metadataCollection.forEach(mod => mod.add(Metadata, false));

let userModulePromise = import("../src/index.ts");

export default (async () => {
  const mod = await userModulePromise;
  return mod;
})();
