import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename)

const configPath = path.resolve(__dirname, '../.buildrc.json');
const config = JSON.parse(fs.readFileSync(configPath, 'utf-8'));

try {
    execSync('npx --version', { stdio: 'ignore' });
    // npx is available, run your command
    execSync('npx @rttist/typegen@0.2.0 generate', { stdio: 'inherit' });
} catch (e) {
    console.error('npx is not available. Please install Node.js with npm >= 5.2.0');
    process.exit(1);
}

const outputDir = path.resolve(__dirname, '../.generated');
fs.mkdirSync(outputDir, { recursive: true });

const wrapperPath = path.join(outputDir, 'index.ts');
const wrapperContent = `
// Auto-generated by prebuild.ts — DO NOT EDIT
import '../.metadata/metadata.index';

import { Metadata } from 'golem-ts-sdk';
import { metadataCollection } from '../.metadata/metadata.index';

metadataCollection.forEach(mod => mod.add(Metadata, false));

let userModulePromise = import("../src/index");

export default (async () => {
  const mod = await userModulePromise;
  return mod;
})();
`;

fs.writeFileSync(wrapperPath, wrapperContent);
