package golem:simulated-agentic-typescript;

interface simulated-agent-ts {
    use golem:agent/common.{data-value, agent-error};

    record weather-agent-record1 {
        data: string,
        value: s32,
    }

    resource assistant-agent {
        constructor();

        ask: func(param1: string) -> result<data-value, agent-error>;
    }

    resource weather-agent {
        constructor();

        get-weather: func(param: string, param2: weather-agent-record1) -> result<data-value, agent-error>;
    }
}

world agentic-world-ts {
    import golem:agent/guest;
    export golem:agent/guest;
    export simulated-agent-ts;
}
